export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as UMass } from "./UMass";
export { default as Favorites } from "./Favorites";
export { default as Places } from "./Places";
export { default as People } from "./people/People";
export { default as Posts } from "./people/Posts";
export { default as Post } from "./people/Post";
export { default as FAQ } from "./FAQ";
export { default as Contact } from "./Contact"
