/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-mobileTeam-iIzFqZv7KH5Wwam7EdcgAG8tWqdvipEP",
  "version": "2020-11-20"
}

export default ebconfig;